version: "3.9"
services:
  postgresql:
    container_name: twp
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpword
      POSTGRES_DB: scrapper
    volumes:
    - postgres-data:/var/lib/postgresql/data
    ports:
    - "5432:5432"
    networks:
    - backend
   
  liquibase-migrations:
    image: liquibase/liquibase:4.18
    depends_on:
       - postgresql
    command:
       - --hub-mode=off
       - --changelog-file=master.xml
       - --driver=org.postgresql.Driver
       - --url=jdbc:postgresql://postgresql:5432/scrapper
       - --username=admin
       - --password=secretpword
       - update
    volumes:
       - ./migrations:/liquibase/changelog
    networks:
       - backend
       
networks:
  backend:

volumes:
  postgres-data: