global:
  scrape_interval: 12s

scrape_configs:
  - job_name: 'scrapper_monitoring'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets:
        - host.docker.internal:8800
        - host.docker.internal:8808

  - job_name: 'bot_monitoring'
    scrape_interval: 5s
    metrics_path: /metrics
    static_configs:
      - targets: [ 'host.docker.internal:8801' ]
