name: Bot CI

on:
  push:
    branches:
      - 'master'
      - 'hw8'
      - 'hw7'
    paths:
      - ".github/workflows/bot.yml"
  pull-request:
    branches:
      - 'master'
      - 'hw8'
      - 'hw7'

jobs:
  build:
    runs-on: ubuntu-latest
    steps: